# To execute this docker-compose file use command - 'docker-compose -f docker-compose_standalone.yml up'
# To stop this docker-compose file use command - 'docker-compose -f docker-compose_standalone.yml down'

version: "3"
services:

  chrome:
    image: selenium/standalone-chrome:latest
    hostname: chrome
    privileged: true
    shm_size: 2gb
    ports:
      - "4441:4444"
      - "7901:7900"
    environment:
      - SE_VNC_NO_PASSWORD=1
      - SE_NODE_MAX_SESSIONS=1

  firefox:
    image: selenium/standalone-firefox:latest
    hostname: firefox
    privileged: true
    shm_size: 2g
    ports:
      - "4442:4444"
      - "7902:7900"
    environment:
      - SE_VNC_NO_PASSWORD=1
      - SE_NODE_MAX_SESSIONS=1
