# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven for Test Automation Framework

on:
  workflow_dispatch:
    inputs:
      browsername:
        type: string
        description: "Enter Browser Name: "
        default: "chrome"
#      xmlfilename:
#        type: string
#        description: "Enter XML filename: "
#        default: "testng_maven.xml"
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build using testng XML files

        #      The below run command will take the browser name and testng XML file name
        #       that were entered from the workflow_dispatch by the user and
        #       use them as arguments while running the mvn clean test
        run: >
          mvn clean test
#               commenting this to avoid confusion
#          -Dsurefire.suiteXmlFiles=${{inputs.xmlfilename}}
          -Dmaven.test.failure.ignore=true

      #        Report Generation
      - name: Archive report artifact
        uses: actions/upload-artifact@v4
        with:
          name: HTMLReport
          path: ./reports/*.html

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
#    - name: Update dependency graph
#      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
