
name: UI Automation Tests

on:
  workflow_dispatch:
    inputs:
      browsername:
        type: string
        description: "Enter Browser Name: "
        default: "chrome"
  #      xmlfilename:
  #        type: string
  #        description: "Enter XML filename: "
  #        default: "testng_maven.xml"
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build and run tests using maven

        #      The below run command will take the browser name and testng XML file name
        #       that were entered from the workflow_dispatch by the user and
        #       use them as arguments while running the mvn clean test
        #
        #               commenting this to avoid confusion
        #          -Dsurefire.suiteXmlFiles=${{inputs.xmlfilename}}
        run: >
          mvn clean test
          -Dmaven.test.failure.ignore=true

      #        Report Generation
      - name: Archive report artifact
        uses: actions/upload-artifact@v4
        with:
          name: HTMLReport
          path: ./reports/*.html

